name: Commit

on:
  workflow_dispatch:
    inputs:
      clean:
        description: "Clean build"
        default: false
        required: false
        type: boolean

env:
  CI_NAME: Commit CI
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      BUILD_ABI: armeabi-v7a,arm64-v8a,x86,x86_64
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fetch JNI cache
        uses: actions/cache@v4
        if: ${{ !github.event.inputs.clean }}
        id: jni-cache
        with:
          path: |
            build-android
            boost
          key: "jni-${{ github.sha }}"

      - name: Fetch submodules
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: |
          git submodule update --init --recursive

      - name: Apply pathches
        run: |
          # Apply patches for librime-qjs
          cd librime-qjs
          git am ../0001-librime-qjs.patch
          cd ../librime/deps/opencc
          git am ../../../0001-opencc.patch

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      # `make debug` works not well on Windows
      - name: Build
        run: |
          python3 make.py build --arch armeabi-v7a
          python3 make.py build --arch arm64-v8a
          python3 make.py build --arch x86
          python3 make.py build --arch x86_64

          - run: |
          mkdir artifacts
          cp -r output/include artifacts/include
          cp -r output/jniLibs artifacts/lib

      - name: Upload JNI artifact
        uses: actions/upload-artifact@v4
        with:
          name: librime_jni
          path: artifacts
          # keep 90 days
          retention-days: 90
