name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      clean:
        description: "Clean build"
        default: false
        required: false
        type: boolean
      v8a_only:
        description: "Only build for arm64-v8a"
        default: false
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Apply pathches
        run: |
          git config --global user.email "cxprcn@gmail.com"
          git config --global user.name "nopdan"
          cd librime-qjs
          git am ../0001-librime-qjs.patch
          cd ../librime/deps/opencc
          git am ../../../0001-opencc.patch

      - name: Cache JNI dependencies
        id: cache-jni
        uses: actions/cache@v4
        with:
          path: |
            build-android
            boost
          key: ${{ runner.os }}-jni-${{ hashFiles('make.py', '**/CMakeLists.txt', '*.patch') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-jni-${{ hashFiles('make.py', '**/CMakeLists.txt', '*.patch') }}-
            ${{ runner.os }}-jni-

      - name: Clean build
        if: ${{ github.event.inputs.clean }}
        run: |
          rm -rf build-android

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.22.x"

      - name: Build arm64-v8a
        run: python3 make.py build --arch arm64-v8a

      - name: Build armeabi-v7a
        if: ${{ !github.event.inputs.v8a_only }}
        run: python3 make.py build --arch armeabi-v7a

      - name: Build x86
        if: ${{ !github.event.inputs.v8a_only }}
        run: python3 make.py build --arch x86

      - name: Build x86_64
        if: ${{ !github.event.inputs.v8a_only }}
        run: python3 make.py build --arch x86_64

      - run: |
          mkdir -p artifacts/opencc
          cp -r output/include artifacts/include
          cp -r output/jniLibs artifacts/lib
          python3 opencc.py
          cp OpenCC/data/dictionary/*.txt artifacts/opencc
          cp OpenCC/data/config/*.json artifacts/opencc

      - name: Upload JNI artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilt
          path: artifacts
          # keep 90 days
          retention-days: 90

      - name: Compress artifacts
        run: |
          cd artifacts
          zip -r prebuilt.zip include lib

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ !github.event.inputs.v8a_only }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "prebuilt"
          prerelease: true
          files: artifacts/prebuilt.zip
